---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: passwords.tomkennedy.dev
spec:
  group: tomkennedy.dev
  scope: Namespaced
  names:
    plural: passwords
    singular: password
    kind: Password
    listKind: PasswordList
    shortNames:
    - pw
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              secrets:
                type: array
                items:
                  type: object
                  required:
                    - secretName
                  properties:
                    secretName:
                      type: string
                    namespace:
                      type: string
              keys:
                type: array
                items:
                  type: object
                  required:
                    - keyName
                  properties:
                    keyName:
                      type: string
                    length:
                      type: integer
                    characterSet:
                      type: string