apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets-default
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets","passwords"]
    verbs: ["list", "get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets-test
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["secrets", "passwords"]
    verbs: ["list", "get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: read-secrets-default
  namespace: default
roleRef:
  kind: Role
  name: read-secrets-default
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: test-service-account
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: read-secrets-test
  namespace: default
roleRef:
  kind: Role
  name: read-secrets-test
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: test-service-account
    namespace: test