---
apiVersion: tomkennedy.dev/v1
kind: Password
metadata:
  name: tom-test
spec:
  secrets:
    - secretName: test
    - secretName: test2
      namespace: test
  keys:
    - keyName: key1
      length: 50
      characterSet: "abcdefghijklmnopqrstuvwxyz1234567890!@#$%^&*()?"

