---
apiVersion: passwordgen.tomkennedy.dev/v1
kind: Password
metadata:
  name: tom-test
spec:
  secrets:
    - secretName: test
  keys:
    - keyName: key1
      length: 23
      characterSet: "abcd"
    - keyName: key2